#
# The Docker image that will be used to build your app
image: alpine
pages:
  script:
    - touch public/$CI_COMMIT_SHA
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - .
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
